robot_name: "anymal_b"
path_to_serow_library: "/usr/local/lib"
topics:
  joint_states: "/joint_states"
  imu: "/imu"
  force_torque_states:
    - "/force_torque_states/lf_foot"
    - "/force_torque_states/rf_foot"
    - "/force_torque_states/lh_foot"
    - "/force_torque_states/rh_foot"
  ground_truth: ""
serow_config: "anymal_b.json" 
