robot_name: "go2"
path_to_serow_library: "/usr/local/lib"
topics:
  joint_states: "/go2/joint_states"
  imu: "/go2/imu"
  force_torque_states:
    - "/go2/LF/force_torque_states"
    - "/go2/LR/force_torque_states"
    - "/go2/RR/force_torque_states"
    - "/go2/RF/force_torque_states"
  ground_truth: ""
  external_odometry: ""
synchronization:
  imu_to_joint: 0.005
  force_torque_to_joint: 0.01
serow_config: "go2.json" 
publish_path: false

