robot_name: "h1"
path_to_serow_library: "/usr/local/lib"
topics:
  joint_states: "/h1/joint_states"
  imu: "/h1/imu"
  force_torque_states:
    - "/h1/left_ankle/force_torque_states"
    - "/h1/right_ankle/force_torque_states"
  ground_truth: ""
  external_odometry: ""
synchronization:
  imu_to_joint: 0.005
  force_torque_to_joint: 0.01
serow_config: "h1.json" 
publish_path: false

